apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-docs
  title: Demo Docs
  description: An example TechDocs documentation for readthedocs theme
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: user:guest