site_name: 'Demo Documentation'
# repo_url: https://github.com/backstage/backstage
# edit_uri: edit/master/plugins/techdocs-backend/examples//docs

nav:
  - Home: index.md
  - Subpage: sub-page.md
  - 'Code Sample': code/code-sample.md
  - Extensions: extensions.md

theme:
  name: material